server:
  port: 8080
  servlet:
    context-path: /demo
#    # 开启Gzip压缩，默认只压缩超过2048字节的数据
#    compression:
#      enabled: true
#      mime-types: application/json
spring:
  redis:
    host: 192.168.100.100
    port: 6379
    password: 123456
    timeout: 5000
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    # 应用名称
    name: SpringBootDemo
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/test-xl?allowMultiQueries:true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456

# 下面这些内容是为了让MyBatis映射
mybatis:
  # 指定Mybatis的Mapper文件
  mapper-locations: classpath:mappers/*xml
  # 指定Mybatis的实体目录
  type-aliases-package: com.hao.entity

# 执行数据库sql打印 下面1、2、3 使用任意一个
logging:
  level:
    # 1
    com.hao.**: debug
    # 解决swagger刷新时转换异常警告
    io.swagger.models.parameters.AbstractSerializableParameter: error
    # 解决controller中方法名重复控制台打印警告
    springfox.documentation.spring.web.readers.operation.CachingOperationNameGenerator: warn
#mybatis-plus:
#  configuration:
#    # 2
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    # 3
#    log-impl: org.apache.ibatis.logging.logging.Slf4jImpl

elasticsearch:
  nodes: 192.168.52.111:9200
  protocol: http
  username: elastic
  password: hao@123
test:
  a: 1
  b: 2
